; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
; upload_port = COM17
build_flags =
	-D CAN_lib_1
	-DENABLE_IMU_LOGGER=1
	-DENABLE_CAN_BRIDGE=0
build_src_filter =
	+<*>
	-<chc_req_bat1.c>
	-<chc_req_controller copy.c>

